USE_BUILDTOOLS := 1
include inc.mk

init = $(call fn_init)
fn_print_test = $(call fn_println, "Print line test")
ifneq ($(fn_print_test), Print line test)
	err := $(error fn_println failed to print string. Got $(fn_print_test))
endif

fn_chklib_test = $(call fn_chklib, SDL2)
ifneq ($(fn_chklib_test),0)
	err := $(error Unable to find SDL2: $(fn_chklib_test))
endif

fn_chklib_test = $(call fn_chklib, badlib)
ifeq ($(fn_chklib_test),0)
	err := $(error Should not have found "badlib" library)
endif

.PHONY: all
all: test.fn_println test.fn_chklib
test.fn_println: inc.mk
	@:

test.fn_chklib: inc.mk
	@:

clean:
	$(RM) test.fn_println
