name: build
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches-ignore:
      - '**pages**'
  pull_request:
    branches-ignore:
      - '**pages**'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [RelWithDebInfo]
        generator: [Ninja]
        include:
          - os: windows-2022
            build_type: RelWithDebInfo
            generator: "NMake Makefiles"
            arch: amd64
            sdk: 8.1
          - os: windows-2022
            build_type: RelWithDebInfo
            generator: "NMake Makefiles"
            arch: amd64_arm64
            sdk: 8.1
          - os: windows-2019
            build_type: RelWithDebInfo
            generator: "NMake Makefiles"
            arch: amd64_x86
            sdk: 7.1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Initialise MSVC environment
        if: "contains(matrix.os, 'windows')"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          sdk: ${{ matrix.sdk }}

      - uses: lukka/get-cmake@latest

      - run: mkdir ${{ env.CPM_SOURCE_CACHE }}

      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CPM_SOURCE_CACHE }}
            ${{ github.workspace }}/build/_deps
            ${{ github.workspace }}/build/**/cmake_pch.*
          key: ${{ matrix.os }}-${{ hashFiles('CMakeLists.txt','.github/workflows/build.yml') }}
          
      - name: Build
        run: |
          cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build
          
      - name: Tar output on Unix systems
        if: "contains(matrix.os, 'windows') == false"
        run: |
          cd ${{ github.workspace }}/build
          tar cf haiyajan.tar haiyajan*

      - name: Get Short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}${{ matrix.arch}}-${{ matrix.build_type }}-${{ steps.vars.outputs.sha_short }}
          path: |
            ${{ github.workspace }}/build/haiyajan.tar
            ${{ github.workspace }}/build/**/haiyajan.exe
            ${{ github.workspace }}/build/**/haiyajan.pdb
